title: xyz digital
author: Adam Berg
email: adam@xyzdigital.com
description: a space for people of all backgrounds to learn more about our digital world
show_excerpts: true
excerpt_separator: <!--more-->

permalink: /stories/:categories/:title

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: UA-168026795-1

rss: Subscribe

webmaster_verifications:
  bing: 7580656E05629A2FB74B9B67926A4F77
  yandex: 150f73e498f7f9f3